2018-12-13T15:26:43|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 219, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 212, in enable_connection
    self.disconnect()
  File "E:\LabPrograms\Python\PI_stage\pi_stage_HW_test.py", line 118, in disconnect
    self.gcs.MOV(self.settings.reference_switch)
AttributeError: 'PIStage' object has no attribute 'gcs'

2018-12-13T15:27:16|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 219, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 212, in enable_connection
    self.disconnect()
  File "E:\LabPrograms\Python\PI_stage\pi_stage_HW_test.py", line 118, in disconnect
    self.gcs.MOV(self.settings.reference_switch)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcscommands.py", line 3104, in MOV
    axes, values = getitemsvaluestuple(axes, values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcscommands.py", line 142, in getitemsvaluestuple
    checksize((True, True), items, values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcscommands.py", line 412, in checksize
    raise TypeError('a required parameter is missing')
TypeError: a required parameter is missing

