2018-12-19T14:40:19|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 160, in <lambda>
    op_button.clicked.connect(lambda checked, f=op_func: f())
  File "E:\LabPrograms\Python\PI_stage\pi_stage_HW_test.py", line 164, in stop
    self.gcs.STP()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcscommands.py", line 2042, in STP
    self.__msgs.send(cmdstr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcsmessages.py", line 120, in send
    self.__checkerror(senderr=not self.__embederr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcsmessages.py", line 278, in __checkerror
    raise exc  # Raising NoneType while only classes or instances are allowed pylint: disable=E0702
pipython.gcserror.GCSError: Controller was stopped by command (10)

2018-12-19T14:40:24|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 160, in <lambda>
    op_button.clicked.connect(lambda checked, f=op_func: f())
  File "E:\LabPrograms\Python\PI_stage\pi_stage_HW_test.py", line 164, in stop
    self.gcs.STP()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcscommands.py", line 2042, in STP
    self.__msgs.send(cmdstr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcsmessages.py", line 120, in send
    self.__checkerror(senderr=not self.__embederr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcsmessages.py", line 278, in __checkerror
    raise exc  # Raising NoneType while only classes or instances are allowed pylint: disable=E0702
pipython.gcserror.GCSError: Controller was stopped by command (10)

2018-12-19T14:40:45|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 160, in <lambda>
    op_button.clicked.connect(lambda checked, f=op_func: f())
  File "E:\LabPrograms\Python\PI_stage\pi_stage_HW_test.py", line 164, in stop
    self.gcs.STP()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcscommands.py", line 2042, in STP
    self.__msgs.send(cmdstr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcsmessages.py", line 120, in send
    self.__checkerror(senderr=not self.__embederr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcsmessages.py", line 278, in __checkerror
    raise exc  # Raising NoneType while only classes or instances are allowed pylint: disable=E0702
pipython.gcserror.GCSError: Controller was stopped by command (10)

2018-12-19T14:41:22|WARNING|LoggedQuantity|x_on_target read_from_hardware called when not connected to hardware
